### ISSUE TITLE
Create descriptive analyses for commuting patterns 

### ISSUE THREAD

**Issue by jaredgreene1** [jaredgreene1/NetworksOfGuatemala#1]
**Goal:** Understand how commuting habits differ across the country based on time and location of calls
**Language:** R
**Tasks:**
- [ ]  Write a model for what the cleaned data columns should be
- [ ] Write scripts to run the data cleaning and grouping
- [ ] Run the data partitioning
- [ ] Write analysis scripts for categorizing the commuters
- [ ] Run analyses and put descriptive stats in a (basic) report
